[package]
name = "hexmap"
version = "0.1.0"
edition = "2024"

[dependencies]
hexx = "0.20.0"
noise = {version = "0.9.0", features = ["images"] }

[dependencies.bevy]
version = "0.16.0"
default-features = false
features = [
    "bevy_gizmos",
    "bevy_sprite",
    "bevy_winit",
]
