[package]
name = "hexmap"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
hexx = "0.20.0"
noise = {version = "0.9.0", features = ["images"] }
rand = "0.9.1"

[dependencies.bevy]
version = "0.16.0"
default-features = false
features = [
    # Core bevy components
    "bevy_gizmos",
    "bevy_sprite",
    "bevy_winit",
    
    # Platform specific (unix)
    "x11",
]

[target.'cfg(target_arch = "wasm32")'.dependencies.bevy]
version = "0.16.0"
default-features = false
features = [
    # Core bevy components
    "bevy_gizmos",
    "bevy_sprite",
    "bevy_winit",

    # Platform specific
    "web",
    "webgl2",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.3.3", features = ["wasm_js"]}
